### PR TITLE
Fixed roomsPerPage parameter

### PR DESCRIPTION
**Pull request by MatissJanis**

### CODE REVIEW

**Comment by tiipiik** [comment]
Whoops, I won't merge this one as changes you made here have already been included in your PR that include Sitemap support.

**Comment by MatissJanis** [comment]
No, these changes were not introduced in that PR. Please check again.

Compare this: https://github.com/tiipiik/OctoberCMS-RoomBooking/pull/2/files
To this: https://github.com/tiipiik/OctoberCMS-RoomBooking/pull/3/files

**Comment by tiipiik** [comment]
Oh yes you're totally right, but I've reintroduced that (from your code) on checking your modifications, so there's no need to merge this one, right ? (I'm a beginner at managing pull requests, but maybe you already see that ^^')

Please let me know if I do something the wrong way.

**Comment by MatissJanis** [comment]
Yeah, I see that the code is LIVE now. Good job! :+1:

**Comment by tiipiik** [comment]
Your welcome, and again, many thanks to you :+1:

**Pull request closed without merging**
